### ISSUE TITLE
Open class and Void events

### ISSUE THREAD

**Issue by marcguilera** [stuhlmeier/kotlin-events#1]
Nice little library. I have two suggestions and I could send a PR if it's something you agree with:

1. Make the event class open so it can be extended
2. Make a void event and allow the invoke param to be optional (for param-free type of events)

**Comment by svby** [comment]
I've addressed the first concern somewhat in the latest release. Additionally, a basic event could be implemented with minimal code by delegating the implementation to a collection instance (see [SetEvent.kt](https://github.com/halcyxn/kotlin-events/blob/master/src/main/kotlin/kotlinx/event/SetEvent.kt))

As for the second, I'm not quite sure how this would fit in with the rest of the library. For a void event, I would just use an `Event<Unit>` and possibly define an extension function as follows:

```kotlin
operator fun Event<Unit>.invoke() = this(Unit)
```

This should satisfy the "parameterless" event use-case.
